// Code generated by MockGen. DO NOT EDIT.
// Source: configuration/configuration_repository.go

// Package configuration is a generated GoMock package.
package configuration

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// getConfiguration mocks base method
func (m *MockRepository) getConfiguration(organizationId int, serviceName, namespace string, version int) (*configView, error) {
	ret := m.ctrl.Call(m, "getConfiguration", organizationId, serviceName, namespace, version)
	ret0, _ := ret[0].(*configView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getConfiguration indicates an expected call of getConfiguration
func (mr *MockRepositoryMockRecorder) getConfiguration(organizationId, serviceName, namespace, version interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getConfiguration", reflect.TypeOf((*MockRepository)(nil).getConfiguration), organizationId, serviceName, namespace, version)
}

// getLatestVersionForNamespace mocks base method
func (m *MockRepository) getLatestVersionForNamespace(organizationId int, serviceName, namespace string) (int, error) {
	ret := m.ctrl.Call(m, "getLatestVersionForNamespace", organizationId, serviceName, namespace)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getLatestVersionForNamespace indicates an expected call of getLatestVersionForNamespace
func (mr *MockRepositoryMockRecorder) getLatestVersionForNamespace(organizationId, serviceName, namespace interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getLatestVersionForNamespace", reflect.TypeOf((*MockRepository)(nil).getLatestVersionForNamespace), organizationId, serviceName, namespace)
}

// createNewVersion mocks base method
func (m *MockRepository) createNewVersion(organizationId int, serviceName, namespace string, config configView, version int) error {
	ret := m.ctrl.Call(m, "createNewVersion", organizationId, serviceName, namespace, config, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// createNewVersion indicates an expected call of createNewVersion
func (mr *MockRepositoryMockRecorder) createNewVersion(organizationId, serviceName, namespace, config, version interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createNewVersion", reflect.TypeOf((*MockRepository)(nil).createNewVersion), organizationId, serviceName, namespace, config, version)
}

// updateNamespaceActiveVersion mocks base method
func (m *MockRepository) updateNamespaceActiveVersion(organizationId int, serviceName, namespace string, version int) error {
	ret := m.ctrl.Call(m, "updateNamespaceActiveVersion", organizationId, serviceName, namespace, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// updateNamespaceActiveVersion indicates an expected call of updateNamespaceActiveVersion
func (mr *MockRepositoryMockRecorder) updateNamespaceActiveVersion(organizationId, serviceName, namespace, version interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "updateNamespaceActiveVersion", reflect.TypeOf((*MockRepository)(nil).updateNamespaceActiveVersion), organizationId, serviceName, namespace, version)
}

// getVersions mocks base method
func (m *MockRepository) getVersions(organizationId int, serviceName, namespace string) ([]int, error) {
	ret := m.ctrl.Call(m, "getVersions", organizationId, serviceName, namespace)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getVersions indicates an expected call of getVersions
func (mr *MockRepositoryMockRecorder) getVersions(organizationId, serviceName, namespace interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getVersions", reflect.TypeOf((*MockRepository)(nil).getVersions), organizationId, serviceName, namespace)
}

// getOrganizationId mocks base method
func (m *MockRepository) getOrganizationId(organizationName string) (int, error) {
	ret := m.ctrl.Call(m, "getOrganizationId", organizationName)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getOrganizationId indicates an expected call of getOrganizationId
func (mr *MockRepositoryMockRecorder) getOrganizationId(organizationName interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getOrganizationId", reflect.TypeOf((*MockRepository)(nil).getOrganizationId), organizationName)
}
